import * as logic from "./logicTwoDimensional.js";
import { BoardHtmlGenerator } from "./boardHtmlGenerator.js";
import { ControlHtmlGenerator } from "./ControlHtmlGenerator.js";
import { SavedBoardsHtmlGenerator } from "./savedBoardsHtmlGenerator.js";
logic.clearLiveCells();
logic.addSimpleGliderGoingUpAndLeft({ rowIndex: 2, columnIndex: 2 });
logic.addSimpleGliderGoingDownAndRight({ rowIndex: 7, columnIndex: 7 });
const startingUpperLeftCell = new logic.Cell(1, 1);
const startingLowerRightCell = new logic.Cell(10, 20);
const startingBoardExtent = new logic.CellExtent(startingUpperLeftCell, startingLowerRightCell);
const rootElement = document.getElementById('root');
// create container elements
const boardContainerElement = document.createElement('p');
const buttonContainerElement = document.createElement('p');
const boardHtmlGenerator = BoardHtmlGenerator(startingBoardExtent, boardContainerElement);
boardHtmlGenerator.updateBoardElement();
const startingIterationCount = 0;
const controlHtmlGenerator = ControlHtmlGenerator(boardHtmlGenerator, startingIterationCount);
buttonContainerElement.appendChild(controlHtmlGenerator.advanceOneStepButtonElement);
buttonContainerElement.appendChild(controlHtmlGenerator.addRowButtonElement);
buttonContainerElement.appendChild(controlHtmlGenerator.addColumnButtonElement);
buttonContainerElement.appendChild(controlHtmlGenerator.resetButtonElement);
buttonContainerElement.appendChild(controlHtmlGenerator.runButtonElement);
rootElement.appendChild(controlHtmlGenerator.ruleDescriptionElement);
rootElement.appendChild(boardContainerElement);
rootElement.appendChild(buttonContainerElement);
rootElement.appendChild(controlHtmlGenerator.saveContainerElement);
const response = await fetch(`/api/boards`);
const savedBoardsJson = await response.json();
const savedBoards = savedBoardsJson.boards;
const savedBoardsHtmlGenerator = SavedBoardsHtmlGenerator();
const savedBoardsElement = savedBoardsHtmlGenerator.getSavedBoardsElement(savedBoards);
rootElement.appendChild(savedBoardsElement);
